"""changes tables

Revision ID: 1c448475d9a6
Revises: 705af8636b1d
Create Date: 2023-09-25 09:33:49.156078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c448475d9a6'
down_revision = '705af8636b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_column('item_price')
        batch_op.drop_column('item_name')
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('item_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('item_price', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
