"""changes tables

Revision ID: 705af8636b1d
Revises: 1e92d8842fca
Create Date: 2023-09-25 09:26:26.374731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705af8636b1d'
down_revision = '1e92d8842fca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_order_history_product_id_products'), 'products', ['product_id'], ['id'])
        batch_op.drop_column('item_name')
        batch_op.drop_column('item_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_price', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('item_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_order_history_product_id_products'), type_='foreignkey')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
