"""creating checkout

Revision ID: 80b3bff66d4c
Revises: ab29162caaf6
Create Date: 2023-09-29 14:56:56.305164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "80b3bff66d4c"
down_revision = "ab29162caaf6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("checkout")
    with op.batch_alter_table("cart_items", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_cart_items_checkout_id_checkout", type_="foreignkey"
        )
        batch_op.drop_column("checkout_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cart_items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("checkout_id", sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(
            "fk_cart_items_checkout_id_checkout", "checkout", ["checkout_id"], ["id"]
        )

    op.create_table(
        "checkout",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("total_price", sa.FLOAT(), nullable=True),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_checkout_user_id_users"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
