"""creating checkout

Revision ID: ab29162caaf6
Revises: 1c448475d9a6
Create Date: 2023-09-29 14:33:00.341572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab29162caaf6'
down_revision = '1c448475d9a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_checkout_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkout_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_cart_items_checkout_id_checkout'), 'checkout', ['checkout_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cart_items_checkout_id_checkout'), type_='foreignkey')
        batch_op.drop_column('checkout_id')

    op.drop_table('checkout')
    # ### end Alembic commands ###
